# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VSky
                                 A QGIS plugin
 ambiant occlusion on DEM to stress out irregularities
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-11
        copyright            : (C) 2020 by Fabrice Monna, Tanguy Rolland
        email                : Fabrice.Monna@u-bourgogne.fr, Tanguy.Rolland@u-bourgogne.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Fabrice Monna, Tanguy Rolland'
__date__ = '2020-10-11'
__copyright__ = '(C) 2020 by Fabrice Monna, Tanguy Rolland'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VSky class from file VSky.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vsky import VSkyPlugin
    return VSkyPlugin()
