# -*- coding: utf-8 -*-

"""
/***************************************************************************
 VSky
                                 A QGIS plugin
 ambiant occlusion on DEM to stress out irregularities
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-11
        copyright            : (C) 2020 by Fabrice Monna, Tanguy Rolland
        email                : Fabrice.Monna@u-bourgogne.fr, Tanguy.Rolland@u-bourgogne.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Fabrice Monna, Tanguy Rolland'
__date__ = '2020-10-11'
__copyright__ = '(C) 2020 by Fabrice Monna, Tanguy Rolland'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import inspect
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessingException,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterBoolean,
                       QgsProcessingAlgorithm,
                       QgsProcessing,
                       )
try:
    import cupy as cp
    CUDA_AVAILABLE = True
except ModuleNotFoundError:
    CUDA_AVAILABLE = False

from . import algorithms

class VSkyAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    MODES = ['vo', 'vop', 'von']
    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    MODE = 'MODE'
    SMOOTHING = 'SMOOTHING'
    RADIUS = 'RADIUS'
    Z_FACTOR = 'Z_FACTOR'
    CUDA = 'CUDA'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(QgsProcessingParameterRasterLayer(self.INPUT,
            self.tr('Elevation Layer')))
        self.addParameter(QgsProcessingParameterEnum(self.MODE,
            self.tr('Processing Method'),
            self.MODES,
            False,
            0,
            False))
        self.addParameter(QgsProcessingParameterNumber(self.SMOOTHING,
            self.tr('Prior smoothing'),
            QgsProcessingParameterNumber.Integer,
            0,
            False,
            0))
        self.addParameter(QgsProcessingParameterNumber(self.RADIUS,
            self.tr('Radius'),
            QgsProcessingParameterNumber.Integer,
            5,
            False,
            2))
        self.addParameter(QgsProcessingParameterNumber(self.Z_FACTOR,
            self.tr('Z factor'),
            QgsProcessingParameterNumber.Double,
            1,
            False,
            0.000001))
        self.addParameter(QgsProcessingParameterRasterDestination(self.OUTPUT,
            self.tr('Output')))
        if CUDA_AVAILABLE:
            self.addParameter(QgsProcessingParameterBoolean(self.CUDA, self.tr('Use CUDA')))


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        input_layer = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        if input_layer is None:
            raise QgsProcessingException(self.invalidSourceError(parameters, self.INPUT))
        if input_layer.crs().isGeographic():
            raise QgsProcessingException(self.tr('The elevation layer must use a projected coordinate reference system.'))
        input_file = input_layer.source()
        mode = self.parameterAsInt(parameters, self.MODE, context)
        smoothing = self.parameterAsInt(parameters, self.SMOOTHING, context)
        z_factor = self.parameterAsDouble(parameters, self.Z_FACTOR, context)
        radius = self.parameterAsInt(parameters, self.RADIUS, context)
        output_file = self.parameterAsOutputLayer(parameters, self.OUTPUT, context)
        use_cuda = CUDA_AVAILABLE and self.parameterAsBool(parameters, self.CUDA, context)

        try:
            output = algorithms.vsky_compute(feedback, self.MODES[mode], input_file, output_file, smoothing=smoothing, z_factor=z_factor, radius=radius, use_cuda=use_cuda)
        except (ValueError, RuntimeError) as error:
            raise QgsProcessingException(str(error)) from error
        return {self.OUTPUT: output}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'vsky'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('vSky')

    def icon(self):
        """
        Should return a QIcon which is used for your algorithm inside
        the Processing toolbox.
        """
        folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(folder, 'vsky-logo.png'))
        return icon


    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'rasterterrainanalysis'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return VSkyAlgorithm()
